config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy'

  namespace :admin do
    resources :posts
    resources :tags, except: [:index]
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators, only: [:index, :edit, :update]
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'pages#home'
  get '/about' => 'pages#about'
  get '/menu' => 'pages#menu'
  get '/beans' => 'pages#beans'
  get '/blog' => 'pages#blog'

end

app/models/moderator.rb
class Moderator < ActiveRecord::Base
    has_secure_password
    
    has_many :posts
    
    validates :fullname, presence: true
    validates :username, presence: true, format: {with: /@/, message: 'is not valid'}
    validates :password, presence: true
end

app/controllers/admin/moderators_controller.rb
class Admin::ModeratorsController < Admin::ApplicationController
    def index
        @moderators = Moderator.all
    end
    
    def edit
        @moderator = Moderator.find(params[:id])
    end
    
    def update
        @moderator = Moderator.find(params[:id])
        
        if @moderator.update(moderator_params)
            flash[:notice] = "Moderator was successfully updated"
            redirect_to admin_moderators_url
        else
            flash[:alert] = "There was a problem updating moderator"
            render 'edit'
        end
        
    end
    
    private
    
    def moderator_params
        params.require(:moderator).permit(:id, :fullname, :username, :password)
    end
end

app/views/admin/moderators/edit.html.erb
<div class="container">

<p><%= render 'validation_errors', object: @moderator %></p>

  <div class="col-md-5 col-md-offset-3">
    <div class="jumbotron vertical-center" id="jumbo">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Edit Moderators</h3>
        </div>
        <div class="panel-body">

            <%= form_for [:admin, @moderator] do |f| %>
                <div class="form-group">
                    <%= f.label :fullname %>
                    <%= f.text_field :fullname, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :username %>
                    <%= f.text_field :username, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :password %>
                    <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
                </div>
                <div class="actions form-group">
                    <%= f.submit "Submit", class: 'btn btn-primary' %>
                </div>
            <% end %>
        </div> <!--panel-body-->
      </div> <!--panel-defalut-->
    </div> <!--jumbotron-->
  </div> <!--col-->
</div> <!--container-->
            

app/views/admin/moderators/index.html.erb
<h1>Moderator's index page</h1>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>fullname</th>
            <th>username</th>
            <th>created</th>
            <th>actions</th>
        </tr>
    </thead>
    <tbody>
        <% @moderators.each do |moderator| %>
            <tr>
                <td><%= moderator.fullname %></td>
                <td><%= moderator.username %></td>
                <td><%= time_ago(moderator.created_at) %></td>
                <td>
                    <%= link_to 'Edit', edit_admin_moderator_path(moderator) %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>