config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy'

  namespace :admin do
    resources :posts
    resources :tags, except: [:index]
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators, only: [:index, :edit, :update]
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'pages#home'
  get '/about' => 'pages#about'
  get '/menu' => 'pages#menu'
  get '/beans' => 'pages#beans'
  get '/blog' => 'pages#blog'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :posts, through: :post_tags

    validates :name, presence: true

    def in_use?
    	PostTag.exists?(tag_id: self.id)
    end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::ApplicationController
  def new
    @tag = Tag.new
    @tags = Tag.all.order(id: :desc)
  end

  def create
    tags_params[:name].split(',').map do |n|
      Tag.new(name: n).save
    end
    redirect_to new_admin_tag_url, notice: 'Tag was successfully created'
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update tags_params
      redirect_to new_admin_tag_url, notice: 'Successfully updated tag'
    else
      flash[:alert] = 'There was a problem updating tag'
      render :edit
    end
  end

  def show
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to :back, notice: 'Successfully deleted tag'
  end

  private

  def tags_params
    params.require(:tag).permit(:id, :name)
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
	def create_deletable_button tag
		if tag.in_use?
			link_to '#' do
				content_tag(:button, 'Delete', class: 'disabled')
			end
		else
			link_to admin_tag_path(tag), method: :delete do
				content_tag(:button, 'Delete')
			end
		end
	end
end

app/views/admin/tags/edit.html.erb
<h1>Admin::Tags#edit</h1>

<%= form_for [:admin, @tag] do |f| %>
	<p><%= f.label :name %></p>
	<p><%= f.text_field :name %></p>
	<p><%= f.submit %></p>
<% end %>

app/views/admin/tags/new.html.erb
<h1>Admin::Tags#new</h1>

<%= form_for [:admin, @tag] do |f| %>
	<p><%= f.text_area :name, placeholder: 'e.g Ruby, Python, Php' %></p>
	<p><%= f.submit %></p>
<% end %>


<table class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>name</th>
			<th>status</th>
			<th>created</th>
			<th>actions</th>
		</tr>
	</thead>
	<tbody>
		<% @tags.each do |tag| %>
			<tr>
				<td><%= tag.name %></td>
				<td><%= status_converter(tag.in_use?, truthy: 'in use', falsey: 'not in use') %></td>
				<td><%= time_ago tag.created_at %></td>
				<td>
					<%= link_to edit_admin_tag_path(tag) do %>
						<button type="button">Edit</button>
					<% end %>

					<%= create_deletable_button tag %>					
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/tags/show.html.erb
<h1>Admin::Tags#show</h1>
<p>Find me in app/views/admin/tags/show.html.erb</p>