config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy'

  namespace :admin do
    resources :posts
    resources :tags, except: [:index]
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators, only: [:index, :edit, :update]
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'pages#home'
  get '/about' => 'pages#about'
  get '/menu' => 'pages#menu'
  get '/beans' => 'pages#beans'
  get '/blog' => 'pages#blog'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  belongs_to :moderator
  
  validates :title, presence: true
  validates :content, presence: true
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  def index
    if params[:search].present?
      @posts = Post.where("title LIKE ? OR content LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%").page params[:page]
    else
      @posts = Post.all.order(id: :desc).page params[:page]
    end
  end

  def new
    @post = Post.new
  end

  def create
    # post = post_params
    # post[:tag_ids].reject! { |p| p.blank? }

    @post = Post.new(post_params)
    @post.moderator_id = current_moderator.id

    if @post.save
      redirect_to admin_posts_url, notice: 'Post was successfully created'
    else
      flash[:alert] = 'There was a problem creating post'
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_posts_url, notice: 'Post was successfully updated'
    else
      flash[:alert] = 'There was a problem updating post'
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to :back, notice: 'Post was successfully deleted'
  end
  
  private
  
  def post_params
    params.require(:post).permit(:id, :title, :content, :publish, tag_ids: [])
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_form.html.erb
<p><%= render 'validation_errors', object: @post %></p>

<%= form_for [:admin, @post] do |f| %>
    <p>
        <%= f.label :title %><br />
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :content %><br />
        <%= f.text_field :content %>
    </p>
    <p>
        <%= f.label :publish %><br />
        <%= f.check_box :publish %>
    </p>
    <p>
        <%= f.select :tag_ids, Tag.all.collect {|t| [t.name, t.id]}, {prompt: 'Select Tag'}, multiple: :true %>
    </p>
    <p><%= f.submit %></p>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Admin::Posts#edit</h1>

<%= render 'form' %>

app/views/admin/posts/index.html.erb
<h1>Admin::Posts#index</h1>
<p><%= link_to 'New Post', new_admin_post_path %></p>

<p>
    <%= form_tag(admin_posts_path, method: :get) do %>
        <%= text_field_tag :search %>
        <%= submit_tag 'Search' %>
    <% end %>
</p>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>title</th>
            <th>publish</th>
            <th>actions</th>
        </tr>
    </thead>
    <tbody>
        
        <% @posts.each do |post| %>
            <tr>
                <td><%= truncate(post.title, length: 60, seperate: '') %></td>
                <td><%= status_converter(post.publish, truthy: 'Active', falsey: 'Pending') %></td>
                <td>
                    <%= link_to 'Edit', edit_admin_post_path(post) %>
                    <%= link_to 'Show', admin_post_path(post) %>
                    <%= link_to 'Delete', admin_post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<p><%= paginate @posts %></p>

app/views/admin/posts/new.html.erb
<h1>Admin::Posts#new</h1>

<%= render 'form' %>

app/views/admin/posts/show.html.erb
<h1>Admin::Posts#show</h1>
<p><b>title:</b> <%= @post.title %></p>
<p><b>content:</b> <%= @post.content %></p>
<p><b>publish:</b> <%= status_converter(@post.publish) %></p>
<p><b>created:</b> <%= time_ago(@post.created_at) %></p>