config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy'

  namespace :admin do
    resources :posts
    resources :tags, except: [:index]
    resources :sessions, only: [:new, :create, :destroy]
    resources :moderators, only: [:index, :edit, :update]
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'pages#home'
  get '/about' => 'pages#about'
  get '/menu' => 'pages#menu'
  get '/beans' => 'pages#beans'
  get '/blog' => 'pages#blog'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  has_many :notifications, as: :notifiable, dependent: :destroy
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/moderator.rb
class Moderator < ActiveRecord::Base
    has_secure_password
    
    has_many :posts
    
    validates :fullname, presence: true
    validates :username, presence: true, format: {with: /@/, message: 'is not valid'}
    validates :password, presence: true
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  belongs_to :moderator
  
  validates :title, presence: true
  validates :content, presence: true
  
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :posts, through: :post_tags

    validates :name, presence: true

    def in_use?
    	PostTag.exists?(tag_id: self.id)
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :notifications, as: :notifiable
  has_many :comments
  has_many :messages
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
         
  def self.find_for_facebook_oauth(auth)
    user = where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
    user
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
end

app/controllers/admin/moderators_controller.rb
class Admin::ModeratorsController < Admin::ApplicationController
    def index
        @moderators = Moderator.all
    end
    
    def edit
        @moderator = Moderator.find(params[:id])
    end
    
    def update
        @moderator = Moderator.find(params[:id])
        
        if @moderator.update(moderator_params)
            flash[:notice] = "Moderator was successfully updated"
            redirect_to admin_moderators_url
        else
            flash[:alert] = "There was a problem updating moderator"
            render 'edit'
        end
        
    end
    
    private
    
    def moderator_params
        params.require(:moderator).permit(:id, :fullname, :username, :password)
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  def index
    if params[:search].present?
      @posts = Post.where("title LIKE ? OR content LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%").page params[:page]
    else
      @posts = Post.all.order(id: :desc).page params[:page]
    end
  end

  def new
    @post = Post.new
  end

  def create
    # post = post_params
    # post[:tag_ids].reject! { |p| p.blank? }

    @post = Post.new(post_params)
    @post.moderator_id = current_moderator.id

    if @post.save
      redirect_to admin_posts_url, notice: 'Post was successfully created'
    else
      flash[:alert] = 'There was a problem creating post'
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_posts_url, notice: 'Post was successfully updated'
    else
      flash[:alert] = 'There was a problem updating post'
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to :back, notice: 'Post was successfully deleted'
  end
  
  private
  
  def post_params
    params.require(:post).permit(:id, :title, :content, :publish, tag_ids: [])
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::ApplicationController
  before_action :authorize, except: [:new, :create]
  
  def new
  end

  def create
    @moderator = Moderator.find_by(username: params[:username]).try(:authenticate, params[:password])
    if @moderator
      session[:current_moderator_id] = @moderator.id
      redirect_to admin_moderators_url, notice: 'You have successfully signed in'
    else
      flash[:alert] = 'There was a problem with your username or password'
      render :new
    end
  end

  def destroy
    session[:current_moderator_id] = nil
    redirect_to '/login', notice: 'You have successfully logged out'
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::ApplicationController
  def new
    @tag = Tag.new
    @tags = Tag.all.order(id: :desc)
  end

  def create
    tags_params[:name].split(',').map do |n|
      Tag.new(name: n).save
    end
    redirect_to new_admin_tag_url, notice: 'Tag was successfully created'
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update tags_params
      redirect_to new_admin_tag_url, notice: 'Successfully updated tag'
    else
      flash[:alert] = 'There was a problem updating tag'
      render :edit
    end
  end

  def show
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to :back, notice: 'Successfully deleted tag'
  end

  private

  def tags_params
    params.require(:tag).permit(:id, :name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def about
    end
    
    def menu
    end
    
    def beans
    end
    
    def blog
    end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
	def create_deletable_button tag
		if tag.in_use?
			link_to '#' do
				content_tag(:button, 'Delete', class: 'disabled')
			end
		else
			link_to admin_tag_path(tag), method: :delete do
				content_tag(:button, 'Delete')
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def status_converter(status, truthy: 'Active', falsey: 'Pending')
        if status
            truthy
        else
            falsey
        end
    end
    
    def time_ago time
        "#{time_ago_in_words(time)} ago"
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Platz Admin</title>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  
</head>
<body>

  <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'PLATZ ADMIN', admin_posts_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="main-nav-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Posts', admin_posts_path %></li>
          <li><%= link_to 'Moderators', admin_moderators_path %></li>
          <li><%= link_to 'Tags', new_admin_tag_path %></li>
          <li><%= link_to 'Logout', logout_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>


  <% if flash[:notice] %>
    <h3 class="bg-primary text-center"><%= flash[:notice] %></h3>
  <% end %>
  <% if flash[:alert] %>
    <h3 class="bg-danger text-center"><%= flash[:alert] %></h3>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Platz</title>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  
</head>
<body>
  <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'PLATZ', root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="main-nav-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Menu', menu_path %></li>
          <li><%= link_to 'Beans', beans_path %></li>
          <li><%= link_to 'Blog', blog_path %></li>
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= image_tag(current_user.image, size: '20x20', style:'border-radius:3px;vertical-align:top;') if current_user.image %>
                  <%= current_user.name %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to edit_user_registration_path do %>
                    <i class="fa fa-edit"></i>
                    My Profile
                    <% end %>
                  </li>
                  <li><%= link_to destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } do %>
                    <i class="fa fa-power-off"></i>
                    Logout
                    <% end %>
                  </li>
                </ul>
              </li>
            <% else %>  
            <li>
              <%= link_to new_user_session_path, method: :get do %>
                <i class="fa fa-user"></i>
                Login
              <% end %>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>

  <div class="container">
    
    

    <%= yield %>
  </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Platz</h1>

app/views/pages/beans.html.erb
<h1>원두소개</h1>

app/views/pages/blog.html.erb
<h1>블로그 페이지</h1>

app/views/pages/home.html.erb
<h1>Platz Home Page</h1>

app/views/pages/menu.html.erb
<h1>메뉴소개</h1>